//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITS.Resources.ResourcesFiles {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MapLabel {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MapLabel() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ITS.Resources.ResourcesFiles.MapLabel", typeof(MapLabel).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abbreviation.
        /// </summary>
        public static string Abbreviation {
            get {
                return ResourceManager.GetString("Abbreviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Denied !!.
        /// </summary>
        public static string AccessDenied {
            get {
                return ResourceManager.GetString("AccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        public static string Admin {
            get {
                return ResourceManager.GetString("Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agenda.
        /// </summary>
        public static string Agenda {
            get {
                return ResourceManager.GetString("Agenda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow.
        /// </summary>
        public static string Allow {
            get {
                return ResourceManager.GetString("Allow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic.
        /// </summary>
        public static string Arabic {
            get {
                return ResourceManager.GetString("Arabic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic Description.
        /// </summary>
        public static string ArabicDescription {
            get {
                return ResourceManager.GetString("ArabicDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic Name.
        /// </summary>
        public static string ArabicName {
            get {
                return ResourceManager.GetString("ArabicName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign.
        /// </summary>
        public static string Assign {
            get {
                return ResourceManager.GetString("Assign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachment.
        /// </summary>
        public static string Attachment {
            get {
                return ResourceManager.GetString("Attachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachment Title.
        /// </summary>
        public static string AttachmentTitle {
            get {
                return ResourceManager.GetString("AttachmentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AttachmentUrl.
        /// </summary>
        public static string AttachmentUrl {
            get {
                return ResourceManager.GetString("AttachmentUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute.
        /// </summary>
        public static string Attribute {
            get {
                return ResourceManager.GetString("Attribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blocked Account.
        /// </summary>
        public static string BlockedAccount {
            get {
                return ResourceManager.GetString("BlockedAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to activeEnglish.
        /// </summary>
        public static string ContentActive {
            get {
                return ResourceManager.GetString("ContentActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Date.
        /// </summary>
        public static string CreateDate {
            get {
                return ResourceManager.GetString("CreateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Group.
        /// </summary>
        public static string CreateGroup {
            get {
                return ResourceManager.GetString("CreateGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Indicator.
        /// </summary>
        public static string CreateIndicator {
            get {
                return ResourceManager.GetString("CreateIndicator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Publisher.
        /// </summary>
        public static string CreatePublisher {
            get {
                return ResourceManager.GetString("CreatePublisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create User.
        /// </summary>
        public static string CreateUser {
            get {
                return ResourceManager.GetString("CreateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete.
        /// </summary>
        public static string DeleteConfirm {
            get {
                return ResourceManager.GetString("DeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted Successfully.
        /// </summary>
        public static string DeletedSuccessfully {
            get {
                return ResourceManager.GetString("DeletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Photo.
        /// </summary>
        public static string DeletePhoto {
            get {
                return ResourceManager.GetString("DeletePhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deny.
        /// </summary>
        public static string Deny {
            get {
                return ResourceManager.GetString("Deny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description Arabic.
        /// </summary>
        public static string Description_A {
            get {
                return ResourceManager.GetString("Description_A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description English.
        /// </summary>
        public static string Description_E {
            get {
                return ResourceManager.GetString("Description_E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string direction {
            get {
                return ResourceManager.GetString("direction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Downloading failed.
        /// </summary>
        public static string DownloadFailed {
            get {
                return ResourceManager.GetString("DownloadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Downloaded Successfully.
        /// </summary>
        public static string DownloadSuccessfully {
            get {
                return ResourceManager.GetString("DownloadSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download XML.
        /// </summary>
        public static string DownloadXml {
            get {
                return ResourceManager.GetString("DownloadXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Email Already In Use.
        /// </summary>
        public static string EmailExist {
            get {
                return ResourceManager.GetString("EmailExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Is Not Valid.
        /// </summary>
        public static string EmailNotValid {
            get {
                return ResourceManager.GetString("EmailNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End IndicatorDate.
        /// </summary>
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Month.
        /// </summary>
        public static string EndMonth {
            get {
                return ResourceManager.GetString("EndMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English Description.
        /// </summary>
        public static string EnglishDescription {
            get {
                return ResourceManager.GetString("EnglishDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English Name.
        /// </summary>
        public static string EnglishName {
            get {
                return ResourceManager.GetString("EnglishName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This User Already Exist.
        /// </summary>
        public static string Exist {
            get {
                return ResourceManager.GetString("Exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There Is Error In File Please Review File Again.
        /// </summary>
        public static string FileError {
            get {
                return ResourceManager.GetString("FileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Focus.
        /// </summary>
        public static string Focus {
            get {
                return ResourceManager.GetString("Focus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Your Password?.
        /// </summary>
        public static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function.
        /// </summary>
        public static string Function {
            get {
                return ResourceManager.GetString("Function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        public static string Group {
            get {
                return ResourceManager.GetString("Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Must Delete Users That Exist In This Goup.
        /// </summary>
        public static string GroupError {
            get {
                return ResourceManager.GetString("GroupError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Name.
        /// </summary>
        public static string GroupName {
            get {
                return ResourceManager.GetString("GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Of.
        /// </summary>
        public static string Groupof {
            get {
                return ResourceManager.GetString("Groupof", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups.
        /// </summary>
        public static string Groups {
            get {
                return ResourceManager.GetString("Groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HiddenInEnglish.
        /// </summary>
        public static string Hidden {
            get {
                return ResourceManager.GetString("Hidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Page.
        /// </summary>
        public static string HomePage {
            get {
                return ResourceManager.GetString("HomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url Not Valid.
        /// </summary>
        public static string HomePageNotValid {
            get {
                return ResourceManager.GetString("HomePageNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string ID {
            get {
                return ResourceManager.GetString("ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Active.
        /// </summary>
        public static string InActive {
            get {
                return ResourceManager.GetString("InActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index Url.
        /// </summary>
        public static string IndexUrl {
            get {
                return ResourceManager.GetString("IndexUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicator.
        /// </summary>
        public static string Indicator {
            get {
                return ResourceManager.GetString("Indicator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IndicatorAttachment.
        /// </summary>
        public static string IndicatorAttachment {
            get {
                return ResourceManager.GetString("IndicatorAttachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicator Date.
        /// </summary>
        public static string IndicatorDate {
            get {
                return ResourceManager.GetString("IndicatorDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicator ID.
        /// </summary>
        public static string IndicatorID {
            get {
                return ResourceManager.GetString("IndicatorID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicator Name.
        /// </summary>
        public static string IndicatorName {
            get {
                return ResourceManager.GetString("IndicatorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicators.
        /// </summary>
        public static string Indicators {
            get {
                return ResourceManager.GetString("Indicators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicator Tracing System.
        /// </summary>
        public static string IndicatorTracingSystem {
            get {
                return ResourceManager.GetString("IndicatorTracingSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inhrit.
        /// </summary>
        public static string Inhrit {
            get {
                return ResourceManager.GetString("Inhrit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Password.
        /// </summary>
        public static string InvalidPassword {
            get {
                return ResourceManager.GetString("InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Username.
        /// </summary>
        public static string Invalidusername {
            get {
                return ResourceManager.GetString("Invalidusername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is Default.
        /// </summary>
        public static string isDefault {
            get {
                return ResourceManager.GetString("isDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Title.
        /// </summary>
        public static string JobTitle {
            get {
                return ResourceManager.GetString("JobTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyword.
        /// </summary>
        public static string Keyword {
            get {
                return ResourceManager.GetString("Keyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Logon Date.
        /// </summary>
        public static string LastLogonDate {
            get {
                return ResourceManager.GetString("LastLogonDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Logout Date.
        /// </summary>
        public static string LastLogoutDate {
            get {
                return ResourceManager.GetString("LastLogoutDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link Group.
        /// </summary>
        public static string LinkGroup {
            get {
                return ResourceManager.GetString("LinkGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List.
        /// </summary>
        public static string List {
            get {
                return ResourceManager.GetString("List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string LogIn {
            get {
                return ResourceManager.GetString("LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name_E.
        /// </summary>
        public static string LookUpName {
            get {
                return ResourceManager.GetString("LookUpName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lookups.
        /// </summary>
        public static string Lookups {
            get {
                return ResourceManager.GetString("Lookups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media.
        /// </summary>
        public static string Media {
            get {
                return ResourceManager.GetString("Media", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News.
        /// </summary>
        public static string News {
            get {
                return ResourceManager.GetString("News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic Notes.
        /// </summary>
        public static string Notes_A {
            get {
                return ResourceManager.GetString("Notes_A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English Notes.
        /// </summary>
        public static string Notes_E {
            get {
                return ResourceManager.GetString("Notes_E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner.
        /// </summary>
        public static string Owner {
            get {
                return ResourceManager.GetString("Owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain at least 8 characters including UPPER/lowercase and numbers.
        /// </summary>
        public static string PasswordValidation {
            get {
                return ResourceManager.GetString("PasswordValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Periodicity.
        /// </summary>
        public static string Periodicity {
            get {
                return ResourceManager.GetString("Periodicity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission.
        /// </summary>
        public static string Permission {
            get {
                return ResourceManager.GetString("Permission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo.
        /// </summary>
        public static string Photo {
            get {
                return ResourceManager.GetString("Photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        public static string Preview {
            get {
                return ResourceManager.GetString("Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information Of.
        /// </summary>
        public static string PreviewTitle {
            get {
                return ResourceManager.GetString("PreviewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publisher.
        /// </summary>
        public static string Publisher {
            get {
                return ResourceManager.GetString("Publisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publishers.
        /// </summary>
        public static string Publishers {
            get {
                return ResourceManager.GetString("Publishers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Records.
        /// </summary>
        public static string Records {
            get {
                return ResourceManager.GetString("Records", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release Date.
        /// </summary>
        public static string ReleaseDate {
            get {
                return ResourceManager.GetString("ReleaseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Name.
        /// </summary>
        public static string ReportName {
            get {
                return ResourceManager.GetString("ReportName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Name Arabic.
        /// </summary>
        public static string ReportName_A {
            get {
                return ResourceManager.GetString("ReportName_A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Name English.
        /// </summary>
        public static string ReportName_E {
            get {
                return ResourceManager.GetString("ReportName_E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Field Is Required.
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restricted.
        /// </summary>
        public static string Restricted {
            get {
                return ResourceManager.GetString("Restricted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save And Add.
        /// </summary>
        public static string SaveAdd {
            get {
                return ResourceManager.GetString("SaveAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save And Edit.
        /// </summary>
        public static string SaveEdit {
            get {
                return ResourceManager.GetString("SaveEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security.
        /// </summary>
        public static string Security {
            get {
                return ResourceManager.GetString("Security", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Object.
        /// </summary>
        public static string selcttObject {
            get {
                return ResourceManager.GetString("selcttObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Group.
        /// </summary>
        public static string SelectGroup {
            get {
                return ResourceManager.GetString("SelectGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        public static string Show {
            get {
                return ResourceManager.GetString("Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Out.
        /// </summary>
        public static string SignOut {
            get {
                return ResourceManager.GetString("SignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social Media.
        /// </summary>
        public static string SocialMedia {
            get {
                return ResourceManager.GetString("SocialMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort Index.
        /// </summary>
        public static string SortIndex {
            get {
                return ResourceManager.GetString("SortIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Indicator Date.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Month.
        /// </summary>
        public static string StartMonth {
            get {
                return ResourceManager.GetString("StartMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template.
        /// </summary>
        public static string Template {
            get {
                return ResourceManager.GetString("Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to textalign.
        /// </summary>
        public static string text {
            get {
                return ResourceManager.GetString("text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to text-align:left.
        /// </summary>
        public static string TextAlign {
            get {
                return ResourceManager.GetString("TextAlign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to textpositionForEnglish.
        /// </summary>
        public static string textposition {
            get {
                return ResourceManager.GetString("textposition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to content_English.
        /// </summary>
        public static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ThisFieldisNotValid.
        /// </summary>
        public static string ThisFieldisNotValid {
            get {
                return ResourceManager.GetString("ThisFieldisNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Field is Required.
        /// </summary>
        public static string ThisFieldisRequired {
            get {
                return ResourceManager.GetString("ThisFieldisRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title Arabic.
        /// </summary>
        public static string Title_A {
            get {
                return ResourceManager.GetString("Title_A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title English.
        /// </summary>
        public static string Title_E {
            get {
                return ResourceManager.GetString("Title_E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        public static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Date.
        /// </summary>
        public static string UploadDate {
            get {
                return ResourceManager.GetString("UploadDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload XML.
        /// </summary>
        public static string UploadXml {
            get {
                return ResourceManager.GetString("UploadXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Can&apos;t Delete This User.
        /// </summary>
        public static string UserError {
            get {
                return ResourceManager.GetString("UserError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Link.
        /// </summary>
        public static string UserLink {
            get {
                return ResourceManager.GetString("UserLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users Of.
        /// </summary>
        public static string UsersOf {
            get {
                return ResourceManager.GetString("UsersOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to website Url.
        /// </summary>
        public static string WebsiteUrl {
            get {
                return ResourceManager.GetString("WebsiteUrl", resourceCulture);
            }
        }
    }
}
